print("Mary had a little {}".format("lamb"))
print("-" * 20, '>' * 3)

# print using index {} formatter fucntion
formatter = "{} {} {} {}"

print(formatter.format(1,2,3,4))
print(formatter.format("one", "two", "three", "last"))

# Triple """ allow to add new lines without using /n character
print("""Line 1......
Line 2 .....
Line 3 .....
Line 4 .....
.....
.....
.....
.....
....
...
..
.
.
.
.""")
